In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

df = pd.read_csv('LoansTrainingSet.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
df.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,Fully Paid,11520,Short Term,741.0,10+ years,Home Mortgage,33694.0,Debt Consolidation,$584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,Fully Paid,3441,Short Term,734.0,4 years,Home Mortgage,42269.0,other,"$1,106.04",26.3,NaN,17,0,6262,19149,0.0,0.0
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,Fully Paid,21029,Short Term,747.0,10+ years,Home Mortgage,90126.0,Debt Consolidation,"$1,321.85",28.8,NaN,5,0,20967,28335,0.0,0.0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,Fully Paid,18743,Short Term,747.0,10+ years,Own Home,38072.0,Debt Consolidation,$751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,Fully Paid,11731,Short Term,746.0,4 years,Rent,50025.0,Debt Consolidation,$355.18,11.5,NaN,12,0,17391,37081,0.0,0.0

In [3]:
df.corr()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
Current Loan Amount,1.000000,-0.139743,0.024069,0.014725,0.003488,-0.003094,-0.000062,0.003138,0.003576,-0.003069
Credit Score,-0.139743,1.000000,-0.033221,-0.011658,-0.007994,0.008124,0.000777,-0.003263,-0.003426,0.004381
Annual Income,0.024069,-0.033221,1.000000,0.146859,-0.059675,0.140463,-0.013672,0.292165,-0.044837,0.038185
Years of Credit History,0.014725,-0.011658,0.146859,1.000000,-0.039695,0.128033,0.061251,0.201001,0.062049,0.020915
Months since last delinquent,0.003488,-0.007994,-0.059675,-0.039695,1.000000,-0.035803,0.088612,-0.024292,0.112907,0.002730
Number of Open Accounts,-0.003094,0.008124,0.140463,0.128033,-0.035803,1.000000,-0.013731,0.222763,-0.022805,0.005754
Number of Credit Problems,-0.000062,0.000777,-0.013672,0.061251,0.088612,-0.013731,1.000000,-0.103814,0.755866,0.584917
Current Credit Balance,0.003138,-0.003263,0.292165,0.201001,-0.024292,0.222763,-0.103814,1.000000,-0.117995,-0.011118
Bankruptcies,0.003576,-0.003426,-0.044837,0.062049,0.112907,-0.022805,0.755866,-0.117995,1.000000,0.046160
Tax Liens,-0.003069,0.004381,0.038185,0.020915,0.002730,0.005754,0.584917,-0.011118,0.046160,1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256984 entries, 0 to 256983
Data columns (total 19 columns):
Loan ID                         256984 non-null object
Customer ID                     256984 non-null object
Loan Status                     256984 non-null object
Current Loan Amount             256984 non-null int64
Term                            256984 non-null object
Credit Score                    195308 non-null float64
Years in current job            245508 non-null object
Home Ownership                  256984 non-null object
Annual Income                   195308 non-null float64
Purpose                         256984 non-null object
Monthly Debt                    256984 non-null object
Years of Credit History         256984 non-null float64
Months since last delinquent    116601 non-null float64
Number of Open Accounts         256984 non-null int64
Number of Credit Problems       256984 non-null int64
Current Credit Balance          256984 non-null int64
Maximum Open Credit             256984 non-null object
Bankruptcies                    256455 non-null float64
Tax Liens                       256961 non-null float64
dtypes: float64(6), int64(4), object(9)
memory usage: 37.3+ MB

In [5]:
df.describe()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
count,2.569840e+05,195308.000000,1.953080e+05,256984.000000,116601.000000,256984.000000,256984.000000,2.569840e+05,256455.000000,256961.000000
mean,1.371331e+07,1251.116099,7.195272e+04,18.290195,34.881450,11.106267,0.156628,1.540656e+04,0.110316,0.027203
std,3.438131e+07,1762.016848,5.887757e+04,7.075747,21.854165,4.982982,0.460731,1.966506e+04,0.336229,0.245950
min,5.050000e+02,585.000000,0.000000e+00,3.400000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,8.299000e+03,714.000000,4.432100e+04,13.500000,16.000000,8.000000,0.000000,5.974000e+03,0.000000,0.000000
50%,1.429800e+04,733.000000,6.124200e+04,17.000000,32.000000,10.000000,0.000000,1.107800e+04,0.000000,0.000000
75%,2.436700e+04,744.000000,8.646200e+04,21.700000,51.000000,14.000000,0.000000,1.931900e+04,0.000000,0.000000
max,1.000000e+08,7510.000000,8.713547e+06,70.500000,176.000000,76.000000,11.000000,1.731412e+06,7.000000,11.000000

In [6]:
df = df[df["Current Loan Amount"] < 100000]

In [7]:
df["Credit Score"] = df["Credit Score"].map(lambda x: x/10 if x > 800 else x)

In [8]:
df.describe()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
count,221774.000000,160098.000000,1.600980e+05,221774.000000,100896.000000,221774.000000,221774.000000,2.217740e+05,221316.000000,221753.000000
mean,13979.687389,720.136466,7.128975e+04,18.248769,34.851302,11.112493,0.156637,1.538249e+04,0.109834,0.027504
std,8260.519207,28.279272,5.841324e+04,7.072319,21.869073,4.981514,0.460165,1.976899e+04,0.335115,0.246730
min,505.000000,585.000000,0.000000e+00,3.700000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,7819.000000,708.000000,4.402325e+04,13.500000,16.000000,8.000000,0.000000,5.991000e+03,0.000000,0.000000
50%,12058.000000,729.000000,6.084650e+04,16.900000,32.000000,10.000000,0.000000,1.109800e+04,0.000000,0.000000
75%,19438.750000,741.000000,8.574000e+04,21.700000,51.000000,14.000000,0.000000,1.930100e+04,0.000000,0.000000
max,41000.000000,751.000000,8.713547e+06,70.500000,176.000000,76.000000,11.000000,1.731412e+06,6.000000,11.000000

In [9]:
df["Monthly Debt"] = df["Monthly Debt"].replace("[\$, ]","",regex = True).astype(float)

In [10]:
df["Loan Status"] = df["Loan Status"].map(lambda x: 1 if x == "Fully Paid" else 0)

In [11]:
df["Loan ID"].value_counts()

fb111476-b40f-4c5d-957d-e19bea1cf4d6    4
e3802022-a6b3-4417-b0fd-ac29dd866d9d    4
3c275ed7-1f5e-4693-b8cc-350e120e1718    4
d1a9b783-f91e-4b34-bbe5-a10bef13d731    4
1e36ee20-f2d5-469c-bc6e-ebec121a1b76    4
09b18b36-0d8e-4616-809c-0cfa529689f7    4
e428a41a-c21a-47c2-b553-3a26ded47b4b    4
9ee15a46-f399-4b95-8a01-b9cfbb5679ae    4
09e9c4a6-f758-47a0-a622-762f2cf83b9d    4
16be66d9-607a-43a4-8fbf-5327a16708c1    4
2c68088b-7e17-4e10-8a87-56287c2b4610    4
0082624f-b513-4485-8b8d-c5d5b6e3b557    4
76104afb-486e-46fb-a7d3-5538e2a5e755    4
c1f6868c-3879-4e83-82af-35d41c827b26    4
02d8479e-b1a1-4d49-9944-258010ff188c    4
4f5f8867-2f7b-43f3-9108-83a619427175    4
53c5513f-25f3-4691-8177-4ba7e273e658    4
05550905-8fcf-4713-bef5-3079c3ec06b9    4
7510feac-5656-4fd2-a302-fbc6ad2b0dbf    4
21833040-001e-43fd-ad6b-b726bd9850f7    4
342b4ed3-40e1-482d-b116-c2ac088a9131    4
655d6698-7703-40cf-9d12-73b7bb89e54b    4
39910b7d-9bc7-4cbf-841d-7859aa850ccd    4
6db1743b-ca56-4475-81c7-7f2d5d55c310    4
e0560454-1b67-487e-9dd3-c7a4a848c218    4
b9de7d83-e5d8-46dc-8fee-63601a5aaa14    4
a7d9c933-0729-4cb0-993b-3627648d0692    4
f14d2349-dd5a-4dfe-a595-912483a27a0d    4
e8fc6a06-a8e0-43e2-b0d8-0dd432fb2904    4
b3eb643a-2dcc-4bf4-b188-4200ef6ac028    4
                                       ..
bc7d14eb-07e7-4432-8caf-e260fcc749b1    1
fc552816-b37e-4630-8ac7-43c24e98d049    1
f989aaa7-c6b1-45cb-b137-3b080c8885d2    1
0bdb93cd-e5d1-4d15-87f3-c39f2a617446    1
3fc751a5-f2ee-41a3-ad80-38ca1634ceed    1
8acdc608-48b2-44fa-a76d-f802a27f2df0    1
3fb5a644-c5d1-49f6-8e97-482617164fa8    1
8bac21c6-51ed-49b9-a98c-e6fb7f539686    1
f31ab27d-7c87-4229-bfa7-627ed73afa0a    1
decfa8e2-c43a-48b6-bbf9-85236a0343f8    1
4eddd31e-71ed-4b3d-8245-d9894341094e    1
0e9a6926-edfe-4785-961f-f3f114b15ce4    1
0393f5f0-0c73-4185-a594-6db88cb3201b    1
9c737dd5-e4c1-4261-81d4-425e87c74295    1
cabfffa3-fb99-48aa-bae5-e6ba0faa1977    1
6a995927-ba3f-4e6c-9987-e0b711f8a41d    1
c4d5bc39-906c-4eac-b2a5-c2a644e54377    1
171634ff-1a08-42ee-bb1b-47b5157adb30    1
0c034f37-8afe-4197-bf6d-8ee06b4b2224    1
c975040a-edca-43d8-8788-d6c9ebc66d24    1
1bd9d241-a043-40ba-a317-0110a5392328    1
10ab9570-c45f-4f82-b531-768416989a77    1
6fc25d36-2a87-4f6d-ab60-10c0c0a3b842    1
d224cac2-ac59-42ec-975c-c5fe39495c0a    1
33112132-f6a0-4dbd-8b60-6d84de8a8735    1
de970996-82c1-438f-9fe6-68f0d0cc0cfb    1
d8eba9f5-ae65-4f0a-80e1-22a87355b96d    1
9fa542c9-0abf-47ed-b02d-cc279082b81b    1
43a7df35-a6dc-438a-ad8c-54a37aaee223    1
67c045a8-3aef-4cae-99c3-0410e9737d56    1
Name: Loan ID, Length: 180490, dtype: int64

In [12]:
df[df["Loan ID"] == "91343210-b13d-405c-b1a9-20429278208d"]

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
146082,91343210-b13d-405c-b1a9-20429278208d,4933b87e-d4eb-49c0-8f1c-a1ba7604ca42,0,18248,Short Term,733.0,7 years,Home Mortgage,45215.0,Debt Consolidation,851.56,18.5,4.0,16,0,13015,56100,0.0,0.0
146083,91343210-b13d-405c-b1a9-20429278208d,4933b87e-d4eb-49c0-8f1c-a1ba7604ca42,0,18248,Short Term,733.0,7 years,Home Mortgage,45215.0,Debt Consolidation,851.56,18.5,4.0,16,0,13015,56100,0.0,0.0
146084,91343210-b13d-405c-b1a9-20429278208d,4933b87e-d4eb-49c0-8f1c-a1ba7604ca42,0,18389,Short Term,NaN,7 years,Home Mortgage,NaN,Debt Consolidation,858.11,18.5,4.0,16,0,13115,56531,0.0,0.0
146085,91343210-b13d-405c-b1a9-20429278208d,4933b87e-d4eb-49c0-8f1c-a1ba7604ca42,0,18389,Short Term,733.0,7 years,Home Mortgage,45563.0,Debt Consolidation,858.11,18.5,4.0,16,0,13115,56531,0.0,0.0

In [13]:

#need to be improoved to keep the row with best data
df["Loan ID"].drop_duplicates(inplace=True)

In [14]:
df["Home Ownership"].unique()

array(['Home Mortgage', 'Own Home', 'Rent', 'HaveMortgage'], dtype=object)

In [15]:
df["Home Ownership"] = df["Home Ownership"].map(lambda x:"Home Mortgage" if x == "HaveMortgage" else x)

In [16]:
df["Purpose"].unique()

array(['Debt Consolidation', 'other', 'Business Loan',
       'Home Improvements', 'Buy House', 'Other', 'Buy a Car',
       'Medical Bills', 'Take a Trip', 'Educational Expenses'],
      dtype=object)

In [17]:
df["Purpose"] = df["Purpose"].map(lambda x:"Other" if x == "other" else x)

In [18]:
df.drop(["Months since last delinquent"], axis=1, inplace=True)

In [35]:
model_df = df[df["Credit Score"].notnull()]

In [36]:
model_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 160098 entries, 0 to 256983
Data columns (total 18 columns):
Loan ID                      160098 non-null object
Customer ID                  160098 non-null object
Loan Status                  160098 non-null int64
Current Loan Amount          160098 non-null int64
Term                         160098 non-null object
Credit Score                 160098 non-null float64
Years in current job         152677 non-null object
Home Ownership               160098 non-null object
Annual Income                160098 non-null float64
Purpose                      160098 non-null object
Monthly Debt                 160098 non-null float64
Years of Credit History      160098 non-null float64
Number of Open Accounts      160098 non-null int64
Number of Credit Problems    160098 non-null int64
Current Credit Balance       160098 non-null int64
Maximum Open Credit          160098 non-null object
Bankruptcies                 159756 non-null float64
Tax Liens                    160085 non-null float64
dtypes: float64(6), int64(5), object(7)
memory usage: 23.2+ MB

In [37]:
X = model_df.drop(["Loan ID", "Customer ID", "Maximum Open Credit", "Bankruptcies", "Tax Liens", "Loan Status", "Monthly Debt"], axis=1)
y = model_df["Loan Status"]

In [38]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 160098 entries, 0 to 256983
Data columns (total 11 columns):
Current Loan Amount          160098 non-null int64
Term                         160098 non-null object
Credit Score                 160098 non-null float64
Years in current job         152677 non-null object
Home Ownership               160098 non-null object
Annual Income                160098 non-null float64
Purpose                      160098 non-null object
Years of Credit History      160098 non-null float64
Number of Open Accounts      160098 non-null int64
Number of Credit Problems    160098 non-null int64
Current Credit Balance       160098 non-null int64
dtypes: float64(3), int64(4), object(4)
memory usage: 14.7+ MB

In [39]:
X = pd.get_dummies(columns=["Term", "Years in current job", "Home Ownership", "Purpose"],data=X)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.20, random_state=42)

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [43]:
# initialize model
log = LogisticRegression()
log.fit(X_train,y_train)

y_pred_log = log.predict(X_test)

acc_log = accuracy_score(y_test,y_pred_log)

print(acc_log)

0.6161149281698938

In [44]:
# Gradient Boosting (boosting)
params = {'n_estimators': 600, "max_depth" : 1, "learning_rate":0.1, "min_samples_leaf":1, "random_state": 42}
gbc = GradientBoostingClassifier(**params)
gbcmodel = gbc.fit(X_train, y_train)

y_predgbc = gbcmodel.predict(X_test)

acc_gbc = accuracy_score(y_predgbc,y_test)

print(acc_gbc)

0.6685196752029982

In [45]:
# Random Forest (bagging)
rf = RandomForestClassifier(n_estimators= 25, max_depth= None, max_features = 0.4, random_state = 42)
rfmodel = rf.fit(X_train, y_train)

y_predrf = rfmodel.predict(X_test)

acc_rf = accuracy_score(y_predrf, y_test)

print(acc_rf)

0.8134915677701436

In [46]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data
# scaling methods: normalization (0 - 1), log
# (x - x_mean)/(x_std)
# zero mean, univariance (variance=1, std=1)
X_scaler = StandardScaler().fit(X_train)

In [47]:
# Transform the training and testing data using the X_scaler

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [50]:
from keras.utils import to_categorical

# One-hot encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

Using TensorFlow backend.

In [58]:
y_train_categorical

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [51]:
# first, create a normal neural network with 2 inputs, 6 hidden nodes, and 2 outputs
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
# hidden layer (1 layer)
model.add(Dense(units=6, activation='relu', input_dim=32)) 
# units is the number of nodes in the hidden layer
# input_dim is the number of features present in the input data

# output layer
model.add(Dense(units=2, activation='softmax'))

In [52]:
# Compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
# adam is a cathegorical alghoritm

In [53]:
# Fit the model to the training data
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 3s - loss: 0.6315 - acc: 0.6518
Epoch 2/100
 - 2s - loss: 0.6097 - acc: 0.6662
Epoch 3/100
 - 2s - loss: 0.6074 - acc: 0.6672
Epoch 4/100
 - 3s - loss: 0.6061 - acc: 0.6677
Epoch 5/100
 - 3s - loss: 0.6055 - acc: 0.6682
Epoch 6/100
 - 3s - loss: 0.6051 - acc: 0.6687
Epoch 7/100
 - 2s - loss: 0.6048 - acc: 0.6697
Epoch 8/100
 - 3s - loss: 0.6044 - acc: 0.6700
Epoch 9/100
 - 2s - loss: 0.6042 - acc: 0.6700
Epoch 10/100
 - 3s - loss: 0.6041 - acc: 0.6702
Epoch 11/100
 - 2s - loss: 0.6037 - acc: 0.6705
Epoch 12/100
 - 3s - loss: 0.6037 - acc: 0.6697
Epoch 13/100
 - 2s - loss: 0.6034 - acc: 0.6709
Epoch 14/100
 - 3s - loss: 0.6032 - acc: 0.6709
Epoch 15/100
 - 3s - loss: 0.6030 - acc: 0.6712
Epoch 16/100
 - 3s - loss: 0.6029 - acc: 0.6711
Epoch 17/100
 - 3s - loss: 0.6029 - acc: 0.6710
Epoch 18/100
 - 3s - loss: 0.6028 - acc: 0.6716
Epoch 19/100
 - 3s - loss: 0.6027 - acc: 0.6710
Epoch 20/100
 - 3s - loss: 0.6026 - acc: 0.6715
Epoch 21/100
 - 3s - loss: 0.6026 - acc: 0.6710
Epoch 22/100
 - 2s - loss: 0.6026 - acc: 0.6718
Epoch 23/100
 - 3s - loss: 0.6025 - acc: 0.6716
Epoch 24/100
 - 3s - loss: 0.6025 - acc: 0.6718
Epoch 25/100
 - 3s - loss: 0.6025 - acc: 0.6714
Epoch 26/100
 - 3s - loss: 0.6026 - acc: 0.6722
Epoch 27/100
 - 3s - loss: 0.6025 - acc: 0.6716
Epoch 28/100
 - 2s - loss: 0.6025 - acc: 0.6723
Epoch 29/100
 - 3s - loss: 0.6024 - acc: 0.6720
Epoch 30/100
 - 3s - loss: 0.6024 - acc: 0.6718
Epoch 31/100
 - 3s - loss: 0.6025 - acc: 0.6719
Epoch 32/100
 - 3s - loss: 0.6023 - acc: 0.6721
Epoch 33/100
 - 3s - loss: 0.6023 - acc: 0.6718
Epoch 34/100
 - 3s - loss: 0.6023 - acc: 0.6719
Epoch 35/100
 - 3s - loss: 0.6022 - acc: 0.6714
Epoch 36/100
 - 3s - loss: 0.6023 - acc: 0.6716
Epoch 37/100
 - 3s - loss: 0.6023 - acc: 0.6716
Epoch 38/100
 - 3s - loss: 0.6023 - acc: 0.6720
Epoch 39/100
 - 3s - loss: 0.6022 - acc: 0.6725
Epoch 40/100
 - 2s - loss: 0.6023 - acc: 0.6721
Epoch 41/100
 - 3s - loss: 0.6023 - acc: 0.6722
Epoch 42/100
 - 3s - loss: 0.6021 - acc: 0.6721
Epoch 43/100
 - 3s - loss: 0.6023 - acc: 0.6718
Epoch 44/100
 - 3s - loss: 0.6022 - acc: 0.6725
Epoch 45/100
 - 3s - loss: 0.6021 - acc: 0.6726
Epoch 46/100
 - 3s - loss: 0.6021 - acc: 0.6721
Epoch 47/100
 - 3s - loss: 0.6022 - acc: 0.6721
Epoch 48/100
 - 4s - loss: 0.6022 - acc: 0.6724
Epoch 49/100
 - 3s - loss: 0.6021 - acc: 0.6728
Epoch 50/100
 - 3s - loss: 0.6021 - acc: 0.6723
Epoch 51/100
 - 3s - loss: 0.6021 - acc: 0.6723
Epoch 52/100
 - 3s - loss: 0.6021 - acc: 0.6727
Epoch 53/100
 - 3s - loss: 0.6021 - acc: 0.6720
Epoch 54/100
 - 3s - loss: 0.6022 - acc: 0.6718
Epoch 55/100
 - 3s - loss: 0.6021 - acc: 0.6730
Epoch 56/100
 - 3s - loss: 0.6021 - acc: 0.6729
Epoch 57/100
 - 3s - loss: 0.6021 - acc: 0.6723
Epoch 58/100
 - 3s - loss: 0.6021 - acc: 0.6723
Epoch 59/100
 - 3s - loss: 0.6020 - acc: 0.6723
Epoch 60/100
 - 3s - loss: 0.6021 - acc: 0.6732
Epoch 61/100
 - 3s - loss: 0.6020 - acc: 0.6728
Epoch 62/100
 - 3s - loss: 0.6021 - acc: 0.6721
Epoch 63/100
 - 3s - loss: 0.6020 - acc: 0.6721
Epoch 64/100
 - 3s - loss: 0.6021 - acc: 0.6719
Epoch 65/100
 - 3s - loss: 0.6020 - acc: 0.6721
Epoch 66/100
 - 3s - loss: 0.6020 - acc: 0.6723
Epoch 67/100
 - 3s - loss: 0.6021 - acc: 0.6725
Epoch 68/100
 - 4s - loss: 0.6021 - acc: 0.6725
Epoch 69/100
 - 3s - loss: 0.6020 - acc: 0.6717
Epoch 70/100
 - 3s - loss: 0.6020 - acc: 0.6717
Epoch 71/100
 - 3s - loss: 0.6020 - acc: 0.6720
Epoch 72/100
 - 3s - loss: 0.6021 - acc: 0.6727
Epoch 73/100
 - 3s - loss: 0.6020 - acc: 0.6724
Epoch 74/100
 - 3s - loss: 0.6020 - acc: 0.6723
Epoch 75/100
 - 3s - loss: 0.6021 - acc: 0.6727
Epoch 76/100
 - 3s - loss: 0.6019 - acc: 0.6725
Epoch 77/100
 - 3s - loss: 0.6020 - acc: 0.6725
Epoch 78/100
 - 3s - loss: 0.6020 - acc: 0.6723
Epoch 79/100
 - 2s - loss: 0.6019 - acc: 0.6718
Epoch 80/100
 - 3s - loss: 0.6020 - acc: 0.6721
Epoch 81/100
 - 2s - loss: 0.6020 - acc: 0.6722
Epoch 82/100
 - 3s - loss: 0.6020 - acc: 0.6725
Epoch 83/100
 - 2s - loss: 0.6020 - acc: 0.6720
Epoch 84/100
 - 3s - loss: 0.6020 - acc: 0.6726
Epoch 85/100
 - 3s - loss: 0.6019 - acc: 0.6721
Epoch 86/100
 - 3s - loss: 0.6020 - acc: 0.6721
Epoch 87/100
 - 3s - loss: 0.6019 - acc: 0.6720
Epoch 88/100
 - 3s - loss: 0.6020 - acc: 0.6719
Epoch 89/100
 - 3s - loss: 0.6020 - acc: 0.6719
Epoch 90/100
 - 3s - loss: 0.6019 - acc: 0.6727
Epoch 91/100
 - 3s - loss: 0.6020 - acc: 0.6721
Epoch 92/100
 - 3s - loss: 0.6019 - acc: 0.6719
Epoch 93/100
 - 3s - loss: 0.6020 - acc: 0.6727
Epoch 94/100
 - 3s - loss: 0.6019 - acc: 0.6720
Epoch 95/100
 - 3s - loss: 0.6020 - acc: 0.6721
Epoch 96/100
 - 3s - loss: 0.6020 - acc: 0.6726
Epoch 97/100
 - 3s - loss: 0.6020 - acc: 0.6716
Epoch 98/100
 - 3s - loss: 0.6020 - acc: 0.6725
Epoch 99/100
 - 3s - loss: 0.6019 - acc: 0.6724
Epoch 100/100
 - 3s - loss: 0.6019 - acc: 0.6719

In [54]:
deep_model = Sequential()
deep_model.add(Dense(units=6, activation='relu', input_dim=32))
deep_model.add(Dense(units=6, activation='relu'))
deep_model.add(Dense(units=2, activation='softmax'))

In [55]:
deep_model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=50,
    shuffle=True,
    verbose=1
)

Epoch 1/50
128078/128078 [==============================] - 3s 26us/step - loss: 0.6229 - acc: 0.6526
Epoch 2/50
128078/128078 [==============================] - 3s 27us/step - loss: 0.6098 - acc: 0.6642
Epoch 3/50
128078/128078 [==============================] - 3s 27us/step - loss: 0.6072 - acc: 0.6676
Epoch 4/50
128078/128078 [==============================] - 3s 26us/step - loss: 0.6057 - acc: 0.6691
Epoch 5/50
128078/128078 [==============================] - 4s 34us/step - loss: 0.6050 - acc: 0.6693
Epoch 6/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6046 - acc: 0.6712
Epoch 7/50
128078/128078 [==============================] - 4s 28us/step - loss: 0.6043 - acc: 0.6701
Epoch 8/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6042 - acc: 0.6709
Epoch 9/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6039 - acc: 0.6713
Epoch 10/50
128078/128078 [==============================] - 4s 28us/step - loss: 0.6036 - acc: 0.6704
Epoch 11/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6035 - acc: 0.6711
Epoch 12/50
128078/128078 [==============================] - 4s 31us/step - loss: 0.6032 - acc: 0.6713
Epoch 13/50
128078/128078 [==============================] - 4s 29us/step - loss: 0.6032 - acc: 0.6714
Epoch 14/50
128078/128078 [==============================] - 4s 31us/step - loss: 0.6030 - acc: 0.6713
Epoch 15/50
128078/128078 [==============================] - 4s 32us/step - loss: 0.6028 - acc: 0.6712
Epoch 16/50
128078/128078 [==============================] - 4s 29us/step - loss: 0.6028 - acc: 0.6708
Epoch 17/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6026 - acc: 0.6707
Epoch 18/50
128078/128078 [==============================] - 4s 31us/step - loss: 0.6026 - acc: 0.6713
Epoch 19/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6026 - acc: 0.6714
Epoch 20/50
128078/128078 [==============================] - 4s 34us/step - loss: 0.6023 - acc: 0.6713
Epoch 21/50
128078/128078 [==============================] - 4s 32us/step - loss: 0.6024 - acc: 0.6708
Epoch 22/50
128078/128078 [==============================] - 4s 29us/step - loss: 0.6023 - acc: 0.6721
Epoch 23/50
128078/128078 [==============================] - 4s 32us/step - loss: 0.6023 - acc: 0.6718
Epoch 24/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6023 - acc: 0.6717: 1s -
Epoch 25/50
128078/128078 [==============================] - 4s 28us/step - loss: 0.6022 - acc: 0.6724
Epoch 26/50
128078/128078 [==============================] - 4s 31us/step - loss: 0.6022 - acc: 0.6719
Epoch 27/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6022 - acc: 0.6724
Epoch 28/50
128078/128078 [==============================] - 4s 29us/step - loss: 0.6020 - acc: 0.6723
Epoch 29/50
128078/128078 [==============================] - 4s 29us/step - loss: 0.6021 - acc: 0.6719
Epoch 30/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6020 - acc: 0.6729
Epoch 31/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6022 - acc: 0.6725: 1s
Epoch 32/50
128078/128078 [==============================] - 4s 31us/step - loss: 0.6021 - acc: 0.6726
Epoch 33/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6020 - acc: 0.6724
Epoch 34/50
128078/128078 [==============================] - 4s 32us/step - loss: 0.6019 - acc: 0.6720
Epoch 35/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6020 - acc: 0.6726
Epoch 36/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6019 - acc: 0.6722
Epoch 37/50
128078/128078 [==============================] - 4s 32us/step - loss: 0.6018 - acc: 0.6722
Epoch 38/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6020 - acc: 0.6721
Epoch 39/50
128078/128078 [==============================] - 4s 32us/step - loss: 0.6019 - acc: 0.6722: 0s - loss: 0.6025 - acc: 0.
Epoch 40/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6019 - acc: 0.6720
Epoch 41/50
128078/128078 [==============================] - 4s 28us/step - loss: 0.6019 - acc: 0.6727
Epoch 42/50
128078/128078 [==============================] - 4s 32us/step - loss: 0.6019 - acc: 0.6719
Epoch 43/50
128078/128078 [==============================] - 4s 34us/step - loss: 0.6017 - acc: 0.6729
Epoch 44/50
128078/128078 [==============================] - 4s 29us/step - loss: 0.6019 - acc: 0.6710
Epoch 45/50
128078/128078 [==============================] - 4s 31us/step - loss: 0.6017 - acc: 0.6728
Epoch 46/50
128078/128078 [==============================] - 4s 33us/step - loss: 0.6019 - acc: 0.6719
Epoch 47/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6018 - acc: 0.6721
Epoch 48/50
128078/128078 [==============================] - 4s 29us/step - loss: 0.6018 - acc: 0.6719
Epoch 49/50
128078/128078 [==============================] - 4s 34us/step - loss: 0.6017 - acc: 0.6722
Epoch 50/50
128078/128078 [==============================] - 4s 30us/step - loss: 0.6018 - acc: 0.6727

In [56]:
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
print(f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 0.6071276668159014, Accuracy: 0.668956901921398

In [57]:
model_loss, model_accuracy = deep_model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Deep Neural Network - Loss: 0.6077581892826645, Accuracy: 0.6688319800124922